### ISSUE TITLE
Step 5 : RUN echo 'root:secret' | chpasswd  ---> Running in 3e912902a146 chpasswd: (user root) pam_chauthtok() failed, error: System error chpasswd: (line 1, user root) password not changed 2015/08/04 05:15:50 The command [/bin/sh -c echo 'root:secret' | chpasswd] returned a non-zero code: 1

### ISSUE THREAD

**Issue by romeokienzler** [streamnsight/docker-flink#2]
I'm getting the following error when building the base image. Maybe the root Image ubuntu:trusty changed?

Step 5 : RUN echo 'root:secret' | chpasswd  ---> Running in 3e912902a146 chpasswd: (user root) pam_chauthtok() failed, error: System error chpasswd: (line 1, user root) password not changed 2015/08/04 05:15:50 The command [/bin/sh -c echo 'root:secret' | chpasswd] returned a non-zero code: 1

**Comment by streamnsight** [comment]
Would have to look into this in more details, but with the newer version of docker you don't really need ssh anymore, so that part could be commented out. 
To run a command into a container you can use the docker exec command like

Docker exe -it <containername> command

To put the jar into the container, mount a volume with a path to your data on the host when you run the container.
In compose that would be something like adding a 
volumes:
- localpath:containerpath

And then you'll have access to the data directly inside the container without the need to scp.
The other option is to use the Web client to load the jar.

I hope this helps until I revise the image.

**Comment by streamnsight** [comment]
Sorry it's
Docker exec -it container command
(The markdown removed my container work in brackets)

**Comment by streamnsight** [comment]
BTW I just tried the image now and it worked fine, so not sure what could be wrong with your case. The ubuntu image most definitely hasn't changed

**Comment by romeokienzler** [comment]
Thanks a lot!!!

Oh, this is funny - I have tried an out of the box Ubuntu

oot@ubuntu:~/docker-flink# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

But I've commented out the setpasswd command and also had to change some relative to absolute paths and it works right now.

I had also to upgrade docker since docker-compose seems to use a newer API version than Ubuntu 14.04
(client and server don't have same version (client : 1.18, server: 1.12))
The solution is described here: http://askubuntu.com/questions/472412/how-do-i-upgrade-docker

I'll now do a little test and then modify docker-compose in order to use the IBM Docker Container Service

**Comment by romeokienzler** [comment]
I've re-run the script as root (previously using sudo) and everything works fine now, thanks a lot for your support!

**Comment by romeokienzler** [comment]
test

**Comment by romeokienzler** [comment]
Sorry, not 100% correct, I had to do the following modification in the Dockerfile for flink
RUN ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
RUN cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/*

> RUN ssh-keygen -f /root/.ssh/id_rsa -t rsa -N ''
> RUN cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys && chmod 600 /root/.ssh/*

Otherwise I get 

docker build -t="flink" flink
Sending build context to Docker daemon 13.82 kB
Sending build context to Docker daemon 
Step 0 : FROM base
 ---> 94deb7ebd45e
Step 1 : RUN ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
 ---> Running in 5ea29031398c
open //.ssh/id_rsa failed: No such file or directory.
Generating public/private rsa key pair.
Saving the key failed: //.ssh/id_rsa.
2015/08/26 06:06:25 The command [/bin/sh -c ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''] returned a non-zero code: 1
